In [4]:
from google.colab import files

uploaded = files.upload()

Saving bulidata.csv to bulidata.csv

In [5]:
import pandas as pd
import sqlite3

# Load dataset
df = pd.read_csv('/content/bulidata.csv')

# Remove unnecessary index column
df = df.drop(columns=['Unnamed: 0'])

df.head()

,MATCH_DATE,LEAGUE_NAME,SEASON,LEAGUE,FINISHED,LOCATION,VIEWER,MATCHDAY,MATCHDAY_NR,HOME_TEAM_ID,...,HOME_ICON,AWAY_TEAM_ID,AWAY_TEAM_NAME,AWAY_TEAM,AWAY_ICON,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
0,2005-08-05 20:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,München,NaN,1. Spieltag,1,40,...,https://i.imgur.com/jJEsJrj.png,87,Borussia Mönchengladbach,Gladbach,https://i.imgur.com/KSIk0Eu.png,3,0,0.0,1.0,0.0
1,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Köln,NaN,1. Spieltag,1,65,...,https://upload.wikimedia.org/wikipedia/en/thum...,81,1. FSV Mainz 05,Mainz,https://upload.wikimedia.org/wikipedia/commons...,1,0,0.0,1.0,0.0
2,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Duisburg,NaN,1. Spieltag,1,107,...,https://upload.wikimedia.org/wikipedia/en/c/c8...,16,VfB Stuttgart,Stuttgart,https://i.imgur.com/v0tkpNx.png,1,1,1.0,0.0,0.0
3,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Hamburg,NaN,1. Spieltag,1,100,...,https://upload.wikimedia.org/wikipedia/commons...,79,1. FC Nürnberg,Nürnberg,https://upload.wikimedia.org/wikipedia/commons...,3,0,0.0,1.0,0.0
4,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Wolfsburg,NaN,1. Spieltag,1,131,...,https://i.imgur.com/ucqKV4B.png,7,Borussia Dortmund,BVB,https://upload.wikimedia.org/wikipedia/commons...,2,2,1.0,0.0,0.0

In [10]:
import pandas as pd
import sqlite3
import os

#Delete old database
if os.path.exists("bundesliga.db"):
    os.remove("bundesliga.db")

#Load dataset
df = pd.read_csv('/content/bulidata.csv')

#Remove index column
df = df.drop(columns=['Unnamed: 0'])

#Create new database
conn = sqlite3.connect('bundesliga.db')

#Store original dataset
df.to_sql('matches', conn, if_exists='replace', index=False)

print("Database created successfully.")
print(df.head())

Database created successfully.
            MATCH_DATE                       LEAGUE_NAME  SEASON LEAGUE  \
0  2005-08-05 20:30:00  1. Fussball-Bundesliga 2005/2006    2005    bl1
1  2005-08-06 15:30:00  1. Fussball-Bundesliga 2005/2006    2005    bl1
2  2005-08-06 15:30:00  1. Fussball-Bundesliga 2005/2006    2005    bl1
3  2005-08-06 15:30:00  1. Fussball-Bundesliga 2005/2006    2005    bl1
4  2005-08-06 15:30:00  1. Fussball-Bundesliga 2005/2006    2005    bl1

   FINISHED   LOCATION  VIEWER     MATCHDAY  MATCHDAY_NR  HOME_TEAM_ID  ...  \
0      True    München     NaN  1. Spieltag            1            40  ...
1      True       Köln     NaN  1. Spieltag            1            65  ...
2      True   Duisburg     NaN  1. Spieltag            1           107  ...
3      True    Hamburg     NaN  1. Spieltag            1           100  ...
4      True  Wolfsburg     NaN  1. Spieltag            1           131  ...

                                           HOME_ICON AWAY_TEAM_ID  \
0                    https://i.imgur.com/jJEsJrj.png           87
1  https://upload.wikimedia.org/wikipedia/en/thum...           81
2  https://upload.wikimedia.org/wikipedia/en/c/c8...           16
3  https://upload.wikimedia.org/wikipedia/commons...           79
4                    https://i.imgur.com/ucqKV4B.png            7

             AWAY_TEAM_NAME  AWAY_TEAM  \
0  Borussia Mönchengladbach   Gladbach
1           1. FSV Mainz 05      Mainz
2             VfB Stuttgart  Stuttgart
3            1. FC Nürnberg   Nürnberg
4         Borussia Dortmund        BVB

                                           AWAY_ICON GOALS_HOME GOALS_AWAY  \
0                    https://i.imgur.com/KSIk0Eu.png          3          0
1  https://upload.wikimedia.org/wikipedia/commons...          1          0
2                    https://i.imgur.com/v0tkpNx.png          1          1
3  https://upload.wikimedia.org/wikipedia/commons...          3          0
4  https://upload.wikimedia.org/wikipedia/commons...          2          2

   DRAW  WIN_HOME  WIN_AWAY
0   0.0       1.0       0.0
1   0.0       1.0       0.0
2   1.0       0.0       0.0
3   0.0       1.0       0.0
4   1.0       0.0       0.0

[5 rows x 22 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5508 entries, 0 to 5507
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MATCH_DATE      5508 non-null   object
 1   LEAGUE_NAME     5508 non-null   object
 2   SEASON          5508 non-null   int64
 3   LEAGUE          5508 non-null   object
 4   FINISHED        5508 non-null   bool
 5   LOCATION        5508 non-null   object
 6   VIEWER          1682 non-null   float64
 7   MATCHDAY        5508 non-null   object
 8   MATCHDAY_NR     5508 non-null   int64
 9   HOME_TEAM_ID    5508 non-null   int64
 10  HOME_TEAM_NAME  5508 non-null   object
 11  HOME_TEAM       5508 non-null   object
 12  HOME_ICON       5508 non-null   object
 13  AWAY_TEAM_ID    5508 non-null   int64
 14  AWAY_TEAM_NAME  5508 non-null   object
 15  AWAY_TEAM       5474 non-null   object
 16  AWAY_ICON       5508 non-null   object
 17  GOALS_HOME      5508 non-null   int64
 18  GOALS_AWAY      5508 non-null   int64
 19  DRAW            5508 non-null   float64
 20  WIN_HOME        5508 non-null   float64
 21  WIN_AWAY        5508 non-null   float64
dtypes: bool(1), float64(4), int64(6), object(11)
memory usage: 909.2+ KB

In [8]:
import sqlite3
import os

# Close any existing connection
try:
    conn.close()
except:
    pass

# Delete old database if it exists
if os.path.exists("bundesliga.db"):
    os.remove("bundesliga.db")

# Create a fresh database connection
conn = sqlite3.connect("bundesliga.db")
cursor = conn.cursor()

In [11]:
teams = pd.concat([
    df[['HOME_TEAM_ID', 'HOME_TEAM_NAME']].rename(
        columns={'HOME_TEAM_ID':'TeamID',
                 'HOME_TEAM_NAME':'TeamName'}),
    df[['AWAY_TEAM_ID', 'AWAY_TEAM_NAME']].rename(
        columns={'AWAY_TEAM_ID':'TeamID',
                 'AWAY_TEAM_NAME':'TeamName'})
]).drop_duplicates()

teams.to_sql('Teams', conn, if_exists='replace', index=False)

display(pd.read_sql_query("SELECT * FROM Teams LIMIT 20", conn))

    TeamID                  TeamName
0       40         FC Bayern München
1       65                1. FC Köln
2      107              MSV Duisburg
3      100              Hamburger SV
4      131             VfL Wolfsburg
5      134             Werder Bremen
6       55               Hannover 96
7        9             FC Schalke 04
8       91       Eintracht Frankfurt
9        6          Bayer Leverkusen
10      87  Borussia Mönchengladbach
11       7         Borussia Dortmund
12      54                Hertha BSC
13      76      1. FC Kaiserslautern
14      79            1. FC Nürnberg
15      83         Arminia Bielefeld
16      16             VfB Stuttgart
17      81           1. FSV Mainz 05
18      93        FC Energie Cottbus
19      23          Alemannia Aachen

In [12]:
seasons = df[['SEASON']].drop_duplicates().reset_index(drop=True)
seasons.index += 1
seasons = seasons.reset_index().rename(
    columns={'index':'SeasonID',
             'SEASON':'Season'})

seasons.to_sql('Seasons', conn, if_exists='replace', index=False)

display(pd.read_sql_query("SELECT * FROM Seasons", conn))

    SeasonID  Season
0          1    2005
1          2    2006
2          3    2007
3          4    2008
4          5    2009
5          6    2010
6          7    2011
7          8    2012
8          9    2013
9         10    2014
10        11    2015
11        12    2016
12        13    2017
13        14    2018
14        15    2019
15        16    2020
16        17    2021
17        18    2022

In [13]:
locations = df[['LOCATION']].dropna().drop_duplicates().reset_index(drop=True)
locations.index += 1
locations = locations.reset_index().rename(
    columns={'index':'LocationID',
             'LOCATION':'Stadium'})

locations.to_sql('Locations', conn, if_exists='replace', index=False)

display(pd.read_sql_query("SELECT * FROM Locations LIMIT 20", conn))

    LocationID         Stadium
0            1         München
1            2            Köln
2            3        Duisburg
3            4         Hamburg
4            5       Wolfsburg
5            6          Bremen
6            7        Hannover
7            8   Gelsenkirchen
8            9       Frankfurt
9           10      Leverkusen
10          11        Gladbach
11          12        Dortmund
12          13          Berlin
13          14  Kaiserslautern
14          15        Nürnberg
15          16       Bielefeld
16          17       Stuttgart
17          18           Mainz
18          19         Cottbus
19          20          Aachen

In [14]:
homewins = df[df['WIN_HOME'] == 1][[
    'HOME_TEAM_NAME',
    'AWAY_TEAM_NAME',
    'GOALS_HOME',
    'GOALS_AWAY'
]].copy()

homewins.index += 1
homewins = homewins.reset_index().rename(
    columns={'index':'MatchID',
             'HOME_TEAM_NAME':'HomeTeam',
             'AWAY_TEAM_NAME':'AwayTeam',
             'GOALS_HOME':'HomeGoals',
             'GOALS_AWAY':'AwayGoals'})

homewins.to_sql('HomeWins', conn, if_exists='replace', index=False)

display(pd.read_sql_query("SELECT * FROM HomeWins LIMIT 20", conn))

,MatchID,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1,FC Bayern München,Borussia Mönchengladbach,3,0
1,2,1. FC Köln,1. FSV Mainz 05,1,0
2,4,Hamburger SV,1. FC Nürnberg,3,0
3,6,Werder Bremen,Arminia Bielefeld,5,2
4,8,FC Schalke 04,1. FC Kaiserslautern,2,1
5,13,Hertha BSC,Eintracht Frankfurt,2,0
6,14,1. FC Kaiserslautern,MSV Duisburg,5,3
7,22,VfL Wolfsburg,Bayer Leverkusen,2,1
8,24,FC Bayern München,Hertha BSC,3,0
9,25,Eintracht Frankfurt,1. FC Nürnberg,1,0
10,27,Arminia Bielefeld,1. FSV Mainz 05,2,0
11,29,Borussia Mönchengladbach,MSV Duisburg,2,1
12,34,Hannover 96,Eintracht Frankfurt,2,0
13,35,Borussia Dortmund,1. FC Köln,2,1
14,36,Hertha BSC,VfL Wolfsburg,3,0
15,37,1. FC Köln,Borussia Mönchengladbach,2,1
16,40,Werder Bremen,Borussia Dortmund,3,2
17,41,FC Bayern München,Hannover 96,1,0
18,46,Borussia Mönchengladbach,Werder Bremen,2,1
19,47,Borussia Dortmund,Arminia Bielefeld,2,0

In [15]:
goalstats = df[[
    'MATCH_DATE',
    'HOME_TEAM_NAME',
    'AWAY_TEAM_NAME',
    'GOALS_HOME',
    'GOALS_AWAY'
]].copy()

goalstats['TotalGoals'] = (
    goalstats['GOALS_HOME'] +
    goalstats['GOALS_AWAY']
)

goalstats.index += 1
goalstats = goalstats.reset_index().rename(
    columns={'index':'StatID',
             'MATCH_DATE':'MatchDate',
             'HOME_TEAM_NAME':'HomeTeam',
             'AWAY_TEAM_NAME':'AwayTeam'})

goalstats.to_sql('GoalStatistics', conn, if_exists='replace', index=False)

display(pd.read_sql_query(
    "SELECT * FROM GoalStatistics LIMIT 20",
    conn))

,StatID,MatchDate,HomeTeam,AwayTeam,GOALS_HOME,GOALS_AWAY,TotalGoals
0,1,2005-08-05 20:30:00,FC Bayern München,Borussia Mönchengladbach,3,0,3
1,2,2005-08-06 15:30:00,1. FC Köln,1. FSV Mainz 05,1,0,1
2,3,2005-08-06 15:30:00,MSV Duisburg,VfB Stuttgart,1,1,2
3,4,2005-08-06 15:30:00,Hamburger SV,1. FC Nürnberg,3,0,3
4,5,2005-08-06 15:30:00,VfL Wolfsburg,Borussia Dortmund,2,2,4
5,6,2005-08-06 15:30:00,Werder Bremen,Arminia Bielefeld,5,2,7
6,7,2005-08-06 15:30:00,Hannover 96,Hertha BSC,2,2,4
7,8,2005-08-07 17:30:00,FC Schalke 04,1. FC Kaiserslautern,2,1,3
8,9,2005-08-07 17:30:00,Eintracht Frankfurt,Bayer Leverkusen,1,4,5
9,10,2005-08-13 15:30:00,Bayer Leverkusen,FC Bayern München,2,5,7
10,11,2005-08-13 15:30:00,Borussia Mönchengladbach,VfL Wolfsburg,1,1,2
11,12,2005-08-13 15:30:00,Borussia Dortmund,FC Schalke 04,1,2,3
12,13,2005-08-13 15:30:00,Hertha BSC,Eintracht Frankfurt,2,0,2
13,14,2005-08-13 15:30:00,1. FC Kaiserslautern,MSV Duisburg,5,3,8
14,15,2005-08-13 15:30:00,1. FC Nürnberg,Hannover 96,1,1,2
15,16,2005-08-13 15:30:00,Arminia Bielefeld,Hamburger SV,0,2,2
16,17,2005-08-14 17:30:00,VfB Stuttgart,1. FC Köln,2,3,5
17,18,2005-08-14 17:30:00,1. FSV Mainz 05,Werder Bremen,0,2,2
18,19,2005-08-27 15:30:00,1. FC Köln,1. FC Kaiserslautern,2,3,5
19,20,2005-08-27 15:30:00,FC Schalke 04,Borussia Mönchengladbach,1,1,2

In [16]:
display(pd.read_sql_query("""
SELECT HOME_TEAM_NAME,
       COUNT(*) AS HomeWins
FROM matches
WHERE WIN_HOME = 1
GROUP BY HOME_TEAM_NAME
ORDER BY HomeWins DESC
""", conn))

              HOME_TEAM_NAME  HomeWins
0          FC Bayern München       221
1          Borussia Dortmund       184
2           Bayer Leverkusen       151
3              FC Schalke 04       144
4              VfL Wolfsburg       134
5   Borussia Mönchengladbach       130
6              Werder Bremen       122
7        Eintracht Frankfurt       113
8              VfB Stuttgart       111
9        TSG 1899 Hoffenheim       102
10           1. FSV Mainz 05       101
11                Hertha BSC        99
12               Hannover 96        86
13              Hamburger SV        83
14               SC Freiburg        81
15                1. FC Köln        74
16               FC Augsburg        72
17                RB Leipzig        69
18            1. FC Nürnberg        54
19                VfL Bochum        35
20        1. FC Union Berlin        35
21         Arminia Bielefeld        33
22        FC Energie Cottbus        20
23        Fortuna Düsseldorf        14
24      1. FC Kaiserslautern        13
25             Karlsruher SC        11
26          FC Ingolstadt 04        10
27           SV Darmstadt 98         9
28           SC Paderborn 07         6
29              MSV Duisburg         6
30          FC Hansa Rostock         5
31    Eintracht Braunschweig         5
32          Alemannia Aachen         5
33              FC St. Pauli         4
34      SpVgg Greuther Fürth         3

In [18]:
display(pd.read_sql_query("""
SELECT SEASON,
       ROUND(AVG(GOALS_HOME + GOALS_AWAY),2)
       AS AvgGoals
FROM matches
GROUP BY SEASON
""", conn))

    SEASON  AvgGoals
0     2005      2.81
1     2006      2.74
2     2007      2.81
3     2008      2.92
4     2009      2.83
5     2010      2.92
6     2011      2.86
7     2012      2.93
8     2013      3.16
9     2014      2.75
10    2015      1.23
11    2016      1.24
12    2017      1.25
13    2018      1.32
14    2019      1.35
15    2020      3.03
16    2021      3.12
17    2022      3.17

In [19]:
display(pd.read_sql_query("""
SELECT t.TeamName,
       COUNT(h.MatchID) AS HomeWins
FROM Teams t
JOIN HomeWins h
ON t.TeamName = h.HomeTeam
GROUP BY t.TeamName
ORDER BY HomeWins DESC
LIMIT 20
""", conn))

                    TeamName  HomeWins
0          FC Bayern München       221
1        TSG 1899 Hoffenheim       204
2          Borussia Dortmund       184
3           Bayer Leverkusen       151
4              FC Schalke 04       144
5              VfL Wolfsburg       134
6   Borussia Mönchengladbach       130
7              Werder Bremen       122
8        Eintracht Frankfurt       113
9              VfB Stuttgart       111
10           1. FSV Mainz 05       101
11                Hertha BSC        99
12               Hannover 96        86
13              Hamburger SV        83
14               SC Freiburg        81
15                1. FC Köln        74
16               FC Augsburg        72
17                RB Leipzig        69
18            1. FC Nürnberg        54
19                VfL Bochum        35

In [20]:
display(pd.read_sql_query("""
SELECT HOME_TEAM_NAME,
       COUNT(*) AS Wins,
       CASE
           WHEN COUNT(*) > 100 THEN 'High'
           WHEN COUNT(*) > 50 THEN 'Medium'
           ELSE 'Low'
       END AS Performance
FROM matches
WHERE WIN_HOME = 1
GROUP BY HOME_TEAM_NAME
ORDER BY Wins DESC
""", conn))

              HOME_TEAM_NAME  Wins Performance
0          FC Bayern München   221        High
1          Borussia Dortmund   184        High
2           Bayer Leverkusen   151        High
3              FC Schalke 04   144        High
4              VfL Wolfsburg   134        High
5   Borussia Mönchengladbach   130        High
6              Werder Bremen   122        High
7        Eintracht Frankfurt   113        High
8              VfB Stuttgart   111        High
9        TSG 1899 Hoffenheim   102        High
10           1. FSV Mainz 05   101        High
11                Hertha BSC    99      Medium
12               Hannover 96    86      Medium
13              Hamburger SV    83      Medium
14               SC Freiburg    81      Medium
15                1. FC Köln    74      Medium
16               FC Augsburg    72      Medium
17                RB Leipzig    69      Medium
18            1. FC Nürnberg    54      Medium
19                VfL Bochum    35         Low
20        1. FC Union Berlin    35         Low
21         Arminia Bielefeld    33         Low
22        FC Energie Cottbus    20         Low
23        Fortuna Düsseldorf    14         Low
24      1. FC Kaiserslautern    13         Low
25             Karlsruher SC    11         Low
26          FC Ingolstadt 04    10         Low
27           SV Darmstadt 98     9         Low
28           SC Paderborn 07     6         Low
29              MSV Duisburg     6         Low
30          FC Hansa Rostock     5         Low
31    Eintracht Braunschweig     5         Low
32          Alemannia Aachen     5         Low
33              FC St. Pauli     4         Low
34      SpVgg Greuther Fürth     3         Low

In [21]:
display(pd.read_sql_query("""
SELECT HOME_TEAM_NAME,
       COUNT(*) AS Wins,
       RANK() OVER(
           ORDER BY COUNT(*) DESC
       ) AS TeamRank
FROM matches
WHERE WIN_HOME = 1
GROUP BY HOME_TEAM_NAME
""", conn))

              HOME_TEAM_NAME  Wins  TeamRank
0          FC Bayern München   221         1
1          Borussia Dortmund   184         2
2           Bayer Leverkusen   151         3
3              FC Schalke 04   144         4
4              VfL Wolfsburg   134         5
5   Borussia Mönchengladbach   130         6
6              Werder Bremen   122         7
7        Eintracht Frankfurt   113         8
8              VfB Stuttgart   111         9
9        TSG 1899 Hoffenheim   102        10
10           1. FSV Mainz 05   101        11
11                Hertha BSC    99        12
12               Hannover 96    86        13
13              Hamburger SV    83        14
14               SC Freiburg    81        15
15                1. FC Köln    74        16
16               FC Augsburg    72        17
17                RB Leipzig    69        18
18            1. FC Nürnberg    54        19
19                VfL Bochum    35        20
20        1. FC Union Berlin    35        20
21         Arminia Bielefeld    33        22
22        FC Energie Cottbus    20        23
23        Fortuna Düsseldorf    14        24
24      1. FC Kaiserslautern    13        25
25             Karlsruher SC    11        26
26          FC Ingolstadt 04    10        27
27           SV Darmstadt 98     9        28
28           SC Paderborn 07     6        29
29              MSV Duisburg     6        29
30          FC Hansa Rostock     5        31
31    Eintracht Braunschweig     5        31
32          Alemannia Aachen     5        31
33              FC St. Pauli     4        34
34      SpVgg Greuther Fürth     3        35

In [22]:
conn.execute("""
CREATE INDEX IF NOT EXISTS idx_team
ON matches(HOME_TEAM_NAME)
""")

display(pd.read_sql_query("""
SELECT HOME_TEAM_NAME,
       COUNT(*) AS MatchesPlayed
FROM matches
GROUP BY HOME_TEAM_NAME
ORDER BY MatchesPlayed DESC
LIMIT 20
""", conn))

              HOME_TEAM_NAME  MatchesPlayed
0           Bayer Leverkusen            306
1          Borussia Dortmund            306
2          FC Bayern München            306
3              VfL Wolfsburg            306
4   Borussia Mönchengladbach            289
5        Eintracht Frankfurt            289
6              FC Schalke 04            289
7              Werder Bremen            289
8            1. FSV Mainz 05            272
9                 Hertha BSC            272
10             VfB Stuttgart            272
11       TSG 1899 Hoffenheim            255
12                1. FC Köln            221
13              Hamburger SV            221
14               Hannover 96            221
15               SC Freiburg            221
16               FC Augsburg            204
17            1. FC Nürnberg            153
18                RB Leipzig            119
19         Arminia Bielefeld            102

In [23]:
query = """
SELECT TEAM, SUM(WINS) AS TOTAL_WINS
FROM (
    SELECT HOME_TEAM_NAME AS TEAM,
           COUNT(*) AS WINS
    FROM matches
    WHERE WIN_HOME = 1
    GROUP BY HOME_TEAM_NAME

    UNION ALL

    SELECT AWAY_TEAM_NAME AS TEAM,
           COUNT(*) AS WINS
    FROM matches
    WHERE WIN_AWAY = 1
    GROUP BY AWAY_TEAM_NAME
)
GROUP BY TEAM
ORDER BY TOTAL_WINS DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                       TEAM  TOTAL_WINS
0         FC Bayern München         393
1         Borussia Dortmund         314
2          Bayer Leverkusen         271
3             VfL Wolfsburg         227
4             FC Schalke 04         223
5             Werder Bremen         208
6  Borussia Mönchengladbach         197
7             VfB Stuttgart         185
8       Eintracht Frankfurt         182
9       TSG 1899 Hoffenheim         170

In [24]:
query = """
SELECT LOCATION,
       COUNT(*) AS MATCHES_PLAYED
FROM matches
GROUP BY LOCATION
ORDER BY MATCHES_PLAYED DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        LOCATION  MATCHES_PLAYED
0         Berlin             340
1      Wolfsburg             306
2        München             306
3     Leverkusen             306
4       Dortmund             306
5       Gladbach             289
6  Gelsenkirchen             289
7      Frankfurt             289
8         Bremen             289
9      Stuttgart             272

In [25]:
query = """
SELECT SEASON,
       ROUND(AVG(DRAW) * 100, 2) AS DRAW_PERCENTAGE
FROM matches
GROUP BY SEASON
ORDER BY SEASON;
"""

pd.read_sql(query, conn)

    SEASON  DRAW_PERCENTAGE
0     2005            31.37
1     2006            25.82
2     2007            25.49
3     2008            24.18
4     2009            28.10
5     2010            20.59
6     2011            25.82
7     2012            25.49
8     2013            20.92
9     2014            26.80
10    2015            40.85
11    2016            43.14
12    2017            35.62
13    2018            38.56
14    2019            35.62
15    2020            26.47
16    2021            23.86
17    2022            24.51

In [26]:
query = """
SELECT
    MATCH_DATE,
    HOME_TEAM_NAME,
    AWAY_TEAM_NAME,
    GOALS_HOME + GOALS_AWAY AS TOTAL_GOALS,

    CASE
        WHEN GOALS_HOME + GOALS_AWAY >= 6 THEN 'High Scoring'
        WHEN GOALS_HOME + GOALS_AWAY >= 3 THEN 'Medium Scoring'
        ELSE 'Low Scoring'
    END AS MATCH_TYPE

FROM matches

LIMIT 20;
"""

pd.read_sql(query, conn)

,MATCH_DATE,HOME_TEAM_NAME,AWAY_TEAM_NAME,TOTAL_GOALS,MATCH_TYPE
0,2005-08-05 20:30:00,FC Bayern München,Borussia Mönchengladbach,3,Medium Scoring
1,2005-08-06 15:30:00,1. FC Köln,1. FSV Mainz 05,1,Low Scoring
2,2005-08-06 15:30:00,MSV Duisburg,VfB Stuttgart,2,Low Scoring
3,2005-08-06 15:30:00,Hamburger SV,1. FC Nürnberg,3,Medium Scoring
4,2005-08-06 15:30:00,VfL Wolfsburg,Borussia Dortmund,4,Medium Scoring
5,2005-08-06 15:30:00,Werder Bremen,Arminia Bielefeld,7,High Scoring
6,2005-08-06 15:30:00,Hannover 96,Hertha BSC,4,Medium Scoring
7,2005-08-07 17:30:00,FC Schalke 04,1. FC Kaiserslautern,3,Medium Scoring
8,2005-08-07 17:30:00,Eintracht Frankfurt,Bayer Leverkusen,5,Medium Scoring
9,2005-08-13 15:30:00,Bayer Leverkusen,FC Bayern München,7,High Scoring
10,2005-08-13 15:30:00,Borussia Mönchengladbach,VfL Wolfsburg,2,Low Scoring
11,2005-08-13 15:30:00,Borussia Dortmund,FC Schalke 04,3,Medium Scoring
12,2005-08-13 15:30:00,Hertha BSC,Eintracht Frankfurt,2,Low Scoring
13,2005-08-13 15:30:00,1. FC Kaiserslautern,MSV Duisburg,8,High Scoring
14,2005-08-13 15:30:00,1. FC Nürnberg,Hannover 96,2,Low Scoring
15,2005-08-13 15:30:00,Arminia Bielefeld,Hamburger SV,2,Low Scoring
16,2005-08-14 17:30:00,VfB Stuttgart,1. FC Köln,5,Medium Scoring
17,2005-08-14 17:30:00,1. FSV Mainz 05,Werder Bremen,2,Low Scoring
18,2005-08-27 15:30:00,1. FC Köln,1. FC Kaiserslautern,5,Medium Scoring
19,2005-08-27 15:30:00,FC Schalke 04,Borussia Mönchengladbach,2,Low Scoring